/**
 * generated by Xtext
 */
package org.fuin.dsl.ddd.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.fuin.dsl.ddd.validation.DomainDrivenDesignDslValidator;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class DomainDrivenDesignDslQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(DomainDrivenDesignDslValidator.INVALID_VAR_NAME)
  public void makeVarNameLowerCase(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        final String firstLetter = xtextDocument.get((_offset).intValue(), 1);
        Integer _offset_1 = issue.getOffset();
        String _lowerCase = firstLetter.toLowerCase();
        xtextDocument.replace((_offset_1).intValue(), 1, _lowerCase);
      }
    };
    acceptor.accept(issue, "First character to lower case", null, null, _function);
  }
  
  @Fix(DomainDrivenDesignDslValidator.REF_TO_AGGREGATE_NOT_ALLOWED)
  public void changeAggregateToId(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    final String idType = _data[0];
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        Integer _length = issue.getLength();
        xtextDocument.replace((_offset).intValue(), (_length).intValue(), idType);
      }
    };
    acceptor.accept(issue, "Change to aggregate ID", null, null, _function);
  }
  
  @Fix(DomainDrivenDesignDslValidator.REF_TO_ENTITY_NOT_ALLOWED)
  public void changeEntityToId(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    final String idType = _data[0];
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        Integer _length = issue.getLength();
        xtextDocument.replace((_offset).intValue(), (_length).intValue(), idType);
      }
    };
    acceptor.accept(issue, "Change to entity ID", null, null, _function);
  }
  
  @Fix(DomainDrivenDesignDslValidator.VO_CANNOT_REF_ENTITY)
  public void changeAbstractEntityToId(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    final String idType = _data[0];
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        Integer _length = issue.getLength();
        xtextDocument.replace((_offset).intValue(), (_length).intValue(), idType);
      }
    };
    acceptor.accept(issue, "Change to entity ID", null, null, _function);
  }
}
