/*
* generated by Xtext
*/
package org.fuin.dsl.ddd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DomainDrivenDesignDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/fuin/dsl/ddd/parser/antlr/internal/InternalDomainDrivenDesignDsl.tokens");
	}
}
