/*
* generated by Xtext
*/
package org.fuin.dsl.ddd.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.fuin.dsl.ddd.services.DomainDrivenDesignDslGrammarAccess;

public class DomainDrivenDesignDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DomainDrivenDesignDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.fuin.dsl.ddd.parser.antlr.internal.InternalDomainDrivenDesignDslParser createParser(XtextTokenStream stream) {
		return new org.fuin.dsl.ddd.parser.antlr.internal.InternalDomainDrivenDesignDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}
	
	public DomainDrivenDesignDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DomainDrivenDesignDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
