/*
 * generated by Xtext 2.11.0.RC2
 */
package org.fuin.dsl.ddd.tests

import com.google.inject.Inject
import org.fuin.dsl.ddd.domainDrivenDesignDsl.DomainModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DomainDrivenDesignDslInjectorProvider)
class DomainDrivenDesignDslParsingTest {
	@Inject
	ParseHelper<DomainModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			context myctx {
			
				namespace mytypes {
					type String
					type Integer
					type List generics 1
			    }
			    
			}
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
