/*
 * generated by Xtext 2.11.0.RC2
 */
package org.fuin.dsl.ddd.ide


/**
 * Use this class to register ide components.
 */
class DomainDrivenDesignDslIdeModule extends AbstractDomainDrivenDesignDslIdeModule {
}
