/**
 * generated by Xtext
 */
package org.fuin.dsl.ddd.ui.contentassist;

import org.fuin.dsl.ddd.ui.contentassist.AbstractDomainDrivenDesignDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DomainDrivenDesignDslProposalProvider extends AbstractDomainDrivenDesignDslProposalProvider {
}
