/*
* generated by Xtext
*/
package org.fuin.dsl.ddd;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DomainDrivenDesignDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.fuin.dsl.ddd.ui.internal.DomainDrivenDesignDslActivator.getInstance().getInjector("org.fuin.dsl.ddd.DomainDrivenDesignDsl");
	}
	
}
