/*
* generated by Xtext
*/
package org.fuin.dsl.ddd;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DomainDrivenDesignDslStandaloneSetup extends DomainDrivenDesignDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DomainDrivenDesignDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

