/*
 * generated by Xtext
 */
package org.fuin.dsl.ddd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainDrivenDesignDslRuntimeModule extends org.fuin.dsl.ddd.AbstractDomainDrivenDesignDslRuntimeModule {

}
