/*
 * generated by Xtext
 */
package org.fuin.dsl.ddd.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.fuin.dsl.ddd.ui.internal.DomainDrivenDesignDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainDrivenDesignDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DomainDrivenDesignDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DomainDrivenDesignDslActivator.getInstance().getInjector(DomainDrivenDesignDslActivator.ORG_FUIN_DSL_DDD_DOMAINDRIVENDESIGNDSL);
	}
	
}
